name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - pruebas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Authenticate with Firebase
        run: firebase login:ci --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Build and deploy
        run: |
          npm install
          npm run build -- --prod
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
